import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppThemeProvider from "@/components/providers/AppThemeProvider";
import { InitColorSchemeScript } from "@mui/material";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: "variable"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="pt-BR" className={inter.variable} suppressHydrationWarning>
      <body>
        <InitColorSchemeScript attribute="class" />
        <AppThemeProvider>{children}</AppThemeProvider>
      </body>
    </html>
  );
}
